# Generated by Django 5.1 on 2024-08-17 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
                ('like', models.BooleanField(default=False)),
                ('Blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs')),
            ],
        ),
    ]
